version: "2"
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - network
    ports:
      - "3000:3000"
      # - "3032:8080"
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432
      RUST_BACKTRACE: 1
      RUST_LOG: info
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-db
    # restart: always
    networks:
      - network
    environment:
      POSTGRES_PASSWORD: secret
networks:
  network:
